DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY auto_increment, AUTHOR BIGINT, GENRE BIGINT, NAME VARCHAR(255), YEAR VARCHAR(4), DESCRIPTION MEDIUMTEXT);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID BIGINT PRIMARY KEY auto_increment, BOOK BIGINT, CONTENT MEDIUMTEXT);
