spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booking
  mongock:
    change-logs-scan-package:
      - ru.diasoft.nixson.changelogs
    enabled: true
    runner-type: InitializingBean

logging:
  level:
    root: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

application:
  locale: ru_RU
