version: '3'
services:
  app:
    build:
#      context: .
      context: ./app
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "9001:9000"
    expose:
      - "9001"
    volumes:
      - ./target:/opt/app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sprint?currentSchema=public
      DB_USER: postgres
      DB_PASSWORD: sprint
      PORT: 9000
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
    - ./initdb/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_PASSWORD: sprint
