spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booking
  resources:
    static-locations: classpath:/static
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: error
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

application:
  locale: ru_RU
