server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  batch:
    job:
      enabled: false
    initialize-schema: always

  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:batchdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      host: localhost
      port: 27017
      database: sbMongo

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.diasoft.nixson.libConvert.changelogs
  enabled: true

logging:
  level:
    org.springframework.jdbc.core: TRACE
    ru.diasoft.nixson.libConvert: DEBUG
