version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    privileged: true
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=booking
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - nw
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - nw
networks:
  nw:
