spring:
  datasource:
    url: jdbc:h2:mem:books
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

application:
  locale: ru_RU
