spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  data:
    rest:
      base-path: /data
      detection-strategy: annotated
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sprint?currentSchema=public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:sprint}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
server:
  port: ${PORT:9001}

logging:
  file:
    name: log.txt
  level:
    root: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,logfile,metrics
